### ISSUE TITLE
Generate documentation for `defcustom` variables

### ISSUE THREAD

**Issue by abougouffa** [mgalgs/make-readme-markdown#13]
Hello,

As Emacs' packages configuration is mostly about customizing variable; I think it would be nice to have documentation generated from `defcustom` and `defvar` declarations.

Translating a declaration like this:

```elisp
(defcustom pkg-name-some-variable "foo"
  "Some documentation about the variable."
  :group 'pkg-name
  :type 'string)
```

To something like:

___

### `pkg-name-some-variable` (`string`)
Some documentation about the variable.

___

Thanks, keep up the good work!

**Comment by mgalgs** [comment]
Great suggestion!

**Comment by mgalgs** [comment]
Suggested previously in #6, so I'm going to close this one, but this is a nice reminder :sweat_smile: I'll try to get to it soon.
